services:
  app:
    build: .
    command: sh -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8085 --reload"
    env_file:
      - .env
    ports:
      - 8085:8085
    restart: always
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=dev_db
    ports:
      - '54353:54352'
    restart: always 
 
